### ISSUE TITLE
Mac can not airdrop to iPhone.

### ISSUE THREAD

**Issue by jazsm** [Lorys89/DELL_OPTIPLEX_3060_MFF#1]
the iPhone  airdrop to the Mac pc is OK, but the Mac PC can not airdrop to the iPhone.

**Comment by jazsm** [comment]
but the Mac PC can not airdrop to the iphone.

**Comment by Lorys89** [comment]
until big sur everything worked fine, with monterey and the new kext bluetoolfixup has changed something, write on acidanthera bugtracker.

**Comment by jazsm** [comment]
How to fix this issue, thanks ! otherwise I will go back to the Big Sur.
