### ISSUE TITLE
ACPI update conflict

### ISSUE THREAD

**Issue by Mic-cosmos** [Lorys89/DELL_OPTIPLEX_3060_MFF#10]
Existing ACPI causes error when trying to use update feature in MacOS Monterey /Ventura.

**Comment by bingdang** [comment]
https://github.com/bingdang/DELLOPTIPLEX_3060_MFF

Support Ventura 13.5.1

**Comment by Lorys89** [comment]
I have sonoma 14.1 b2 installed, I need to update the repo
