### ISSUE TITLE
Hello, boss

### ISSUE THREAD

**Issue by bingdang** [Lorys89/DELL_OPTIPLEX_3060_MFF#6]
Can this EFI directly upgrade Ventura 13.0

**Comment by bingdang** [comment]
![image](https://user-images.githubusercontent.com/63091981/199635819-9fd15d51-c250-4054-a5d1-a3913c875ad5.png)

**Comment by Lorys89** [comment]
No, wait for Monday release for 0.8.6

**Comment by bingdang** [comment]
Look forward to your masterpiece, Thank you😄
