### ISSUE TITLE
update to macOS Ventura ?

### ISSUE THREAD

**Issue by geneyuriy** [Lorys89/DELL_OPTIPLEX_3060_MFF#8]
A new version of macOS has been released, are you considering upgrading this computer's system to macOS Ventura? Looking forward to you sharing the new EFI files

**Comment by Lorys89** [comment]
I use ventura from the first beta on this pc, take the efi and update oc and kext and you can run ventura..

**Comment by ozomandis** [comment]
Wifi and Bluetooth is not working on Ventura. With the same wifi card and kext.

**Comment by Lorys89** [comment]
update to macos tahoe beta
